<?php
$_helper = $this->helper('WeltPixel\QuickCart\Helper\Data');
$cspNonceProvider = $_helper->getCspNonceProvider();
?>
<?php if ($_helper->quicartIsEnabled()): ?>
    <script<?php if ($cspNonceProvider): ?> nonce="<?= $block->escapeHtmlAttr($cspNonceProvider->generateNonce()) ?>"<?php endif; ?>>
        window.openMinicart = '<?= $block->escapeJs((string)$_helper->openMinicart()) ?>';
        window.shouldOpenMinicart = '1';
        window.openMinicartDisplayOptions = '<?= $block->escapeJs((string)$_helper->getQuickCartDisplayOptions()) ?>';
        requirejs(['jquery', 'weltpixel_quickcart' ], function($, quickcart) {
            $(document).ready(function() {
                var mobileBreakpoint = <?= (int)$_helper->getMobileBreakPoint() ?>;
                quickcart.initialize(mobileBreakpoint);
            });
        });
    </script>
<?php endif; ?>
