<?php
// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */

/** @var \WeltPixel\QuickCart\Helper\Data $_helper */
$_helper = $this->helper('WeltPixel\QuickCart\Helper\Data');
$cspNonceProvider = $_helper->getCspNonceProvider();
?>

<div data-block="minicart" class="minicart-wrapper quickcart-wrapper minicart-weltpixel">
    <a class="action showcart" href="<?php /* @noEscape */ echo $block->getShoppingCartUrl(); ?>"
       data-bind="scope: 'minicart_content'">
        <span class="text"><?php /* @noEscape */ echo __('My Cart'); ?></span>
        <span class="counter qty empty"
              data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
            <span class="counter-number"><!-- ko text: getCartParam('summary_count') --><!-- /ko --></span>
            <span class="counter-label">
            <!-- ko if: getCartParam('summary_count') -->
                <!-- ko text: getCartParam('summary_count') --><!-- /ko -->
                <!-- ko i18n: 'items' --><!-- /ko -->
                <!-- /ko -->
            </span>
        </span>
    </a>
    <?php if ($block->getIsNeedToDisplaySideBar()): ?>
        <div class="block block-minicart block-quickcart empty"
             data-role="dropdownDialog"
             data-mage-init='{"dropdownDialog":{
                "appendTo":"[data-block=minicart]",
                "triggerTarget":".showcart",
                "timeout": "2000",
                "closeOnMouseLeave": false,
                "closeOnEscape": true,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":[]}}'
        >
                <div id="minicart-content-wrapper" class="quickcart-content-wrapper" data-bind="scope: 'minicart_content'">
                    <!-- ko template: getTemplate() --><!-- /ko -->
                </div>
            <?php echo $block->getChildHtml('minicart.addons'); ?>
        </div>
    <?php endif ?>
    <script<?php if ($cspNonceProvider): ?> nonce="<?= $block->escapeHtmlAttr($cspNonceProvider->generateNonce()) ?>"<?php endif; ?>>
        window.checkout = <?php /* @noEscape */ echo json_encode($block->getConfig()); ?>;
    </script>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?php /* @noEscape */ echo $block->getJsLayout();?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?php /* @noEscape */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
        }
    }
    </script>

    <?php $_helper = $this->helper('WeltPixel\QuickCart\Helper\Data'); ?>
    <?php $storeId = $_helper->getStoreId(); ?>
    <style>
        .block-content-quickcart .quickcart-top {
            background: <?php /* @noEscape */  echo $_helper->getHeaderBackground($storeId) ?>;
            color: <?php /* @noEscape */  echo $_helper->getHeaderTextColor($storeId) ?>;
            height: <?php /* @noEscape */  echo $_helper->getHeaderHeight($storeId) ?>;
            line-height: <?php /* @noEscape */  echo $_helper->getHeaderHeight($storeId) ?>;
        }
        .block-content-quickcart .quickcart-top button.close {
            height: <?php /* @noEscape */  echo $_helper->getHeaderHeight($storeId) ?>;
        }
        .block-content-quickcart .quickcart-top button.close span {
            color: <?php /* @noEscape */  echo $_helper->getHeaderTextColor($storeId) ?>;
        }
        .block-content-quickcart .quickcart-top .action.close::before {
            color: <?php /* @noEscape */  echo $_helper->getHeaderTextColor($storeId) ?>;
        }
        .block-content-quickcart .quickcart-bottom-container .subtotal {
            background: <?php /* @noEscape */  echo $_helper->getSubtotalBackground($storeId) ?>;
            color: <?php /* @noEscape */  echo $_helper->getSubtotalTextColor($storeId) ?>;
        }
        .block-content-quickcart .quickcart-bottom-container .grand_total {
            background: <?php /* @noEscape */  echo $_helper->getGrandTotalBackground($storeId) ?>;
            color: <?php /* @noEscape */  echo $_helper->getGrandTotalTextColor($storeId) ?>;
        }
        <?php if ($_helper->isQuickCartMessageEnabled($storeId)) : ?>
        .header .quickcart-wrapper .block-quickcart .block-content-quickcart .quickcart-bottom-container .custom-msg-wrapper .custom-msg,
        .header .quickcart-wrapper .block-quickcart .block-content-quickcart .quickcart-bottom-container .custom-msg-wrapper .custom-msg span{
            color: <?php /* @noEscape */  echo $_helper->getQuickCartMessageTextColor($storeId) ?>;
            font-size: <?php /* @noEscape */  echo $_helper->getQuickCartMessageFontSize($storeId) ?>;
        }
        <?php $customCss = $_helper->getQuickCartMessageCustomCss(); ?>
        <?php if (strlen($customCss)): ?>
        <?php /* @noEscape */  echo $customCss; ?>
        <?php endif; ?>
        .header .quickcart-wrapper .block-quickcart .block-content-quickcart .quickcart-items-wrapper {
            height: <?= /* @noEscape */  $_helper->getQuickCartItemWrapperHeight(); ?>
        }
        <?php endif; ?>

        <?php if ($_helper->isCarouselEnabled()) : ?>
        .header .quickcart-wrapper .block-quickcart .block-content-quickcart .quickcart-bottom-container .quickcart-carousel-wrapper .quickcart-carosuel-title{
            color: <?= /* @noEscape */  $_helper->getCarouselTitleColor() ?>;
            font-size: <?= /* @noEscape */  $_helper->getCarouselTitleFontSize(); ?>
        }
        .header .quickcart-wrapper .block-quickcart .block-content-quickcart .quickcart-bottom-container .quickcart-carousel-wrapper .owl-theme .owl-controls .owl-nav [class*=owl-].owl-prev,
        .header .quickcart-wrapper .block-quickcart .block-content-quickcart .quickcart-bottom-container .quickcart-carousel-wrapper .owl-theme .owl-controls .owl-nav [class*=owl-].owl-next {
            border-radius: <?= /* @noEscape */  $_helper->getCarouselArrowsBorderRadius() ?>;
            -moz-border-radius: <?= /* @noEscape */  $_helper->getCarouselArrowsBorderRadius() ?>;
            -webkit-border-radius: <?= /* @noEscape */  $_helper->getCarouselArrowsBorderRadius() ?>;
            background-color: <?= /* @noEscape */  $_helper->getCarouselArrowsBackground() ?>;
        }
        .header .quickcart-wrapper .block-quickcart .block-content-quickcart .quickcart-bottom-container .quickcart-carousel-wrapper .owl-theme .owl-controls .owl-nav [class*=owl-].owl-prev:before,
        .header .quickcart-wrapper .block-quickcart .block-content-quickcart .quickcart-bottom-container .quickcart-carousel-wrapper .owl-theme .owl-controls .owl-nav [class*=owl-].owl-next:before {
            background-color: <?= /* @noEscape */  $_helper->getCarouselArrowsColor() ?>;
        }
        .header .quickcart-wrapper .block-quickcart .block-content-quickcart .quickcart-bottom-container .quickcart-carousel-wrapper  .owl-theme .owl-controls .owl-nav [class*=owl-]:hover {
            background-color: <?= /* @noEscape */  $_helper->getCarouselArrowsHoverBackground() ?>;
        }
        .header .quickcart-wrapper .block-quickcart .block-content-quickcart .quickcart-bottom-container .quickcart-carousel-wrapper .owl-theme .owl-controls .owl-nav [class*=owl-].owl-prev:hover:before,
        .header .quickcart-wrapper .block-quickcart .block-content-quickcart .quickcart-bottom-container .quickcart-carousel-wrapper .owl-theme .owl-controls .owl-nav [class*=owl-].owl-next:hover:before {
            background-color: <?= /* @noEscape */  $_helper->getCarouselArrowsHoverColor() ?>;
        }
        <?php endif; ?>
    </style>
</div>
